name: Lint

# Grabbed from https://black.readthedocs.io/en/stable/github_actions.html

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
